# Generated by Django 3.0.5 on 2024-05-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krist_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
