# Generated by Django 3.0.5 on 2024-05-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krist_app', '0002_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_address', models.CharField(max_length=200)),
                ('user_moblieno', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_qty', models.IntegerField()),
            ],
        ),
    ]
